.PHONY: clean All

All:
	@echo "----------Building project:[ intro_array - Debug ]----------"
	@cd "intro_array" && "$(MAKE)" -f  "intro_array.mk"
clean:
	@echo "----------Cleaning project:[ intro_array - Debug ]----------"
	@cd "intro_array" && "$(MAKE)" -f  "intro_array.mk" clean
