.PHONY: clean All

All:
	@echo "----------Building project:[ tree_recursion - Debug ]----------"
	@cd "tree_recursion" && "$(MAKE)" -f  "tree_recursion.mk"
clean:
	@echo "----------Cleaning project:[ tree_recursion - Debug ]----------"
	@cd "tree_recursion" && "$(MAKE)" -f  "tree_recursion.mk" clean
