.PHONY: clean All

All:
	@echo "----------Building project:[ array2_adt - Debug ]----------"
	@cd "array2_adt" && "$(MAKE)" -f  "array2_adt.mk"
clean:
	@echo "----------Cleaning project:[ array2_adt - Debug ]----------"
	@cd "array2_adt" && "$(MAKE)" -f  "array2_adt.mk" clean
