.PHONY: clean All

All:
	@echo "----------Building project:[ 2D_array - Debug ]----------"
	@cd "2D_array" && "$(MAKE)" -f  "2D_array.mk"
clean:
	@echo "----------Cleaning project:[ 2D_array - Debug ]----------"
	@cd "2D_array" && "$(MAKE)" -f  "2D_array.mk" clean
