.PHONY: clean All

All:
	@echo "----------Building project:[ pointer - Debug ]----------"
	@cd "pointer" && "$(MAKE)" -f  "pointer.mk"
clean:
	@echo "----------Cleaning project:[ pointer - Debug ]----------"
	@cd "pointer" && "$(MAKE)" -f  "pointer.mk" clean
